/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
        'primary-container': 'var(--primary-container)',
        'primary-dim': 'var(--primary-container)',
        'primary-fixed': 'var(--primary-container)',
        'primary-fixed-dim': 'var(--primary)',
        'on-primary': 'var(--on-primary)',
        'on-primary-container': 'var(--on-primary)',
        'on-primary-fixed': 'var(--on-primary)',
        'on-primary-fixed-variant': 'var(--on-primary)',
        'inverse-primary': 'var(--primary)',

        secondary: 'var(--secondary)',
        'secondary-container': 'var(--secondary)',
        'secondary-fixed': 'var(--secondary)',
        'secondary-fixed-dim': 'var(--secondary)',
        'secondary-dim': 'var(--secondary)',
        'on-secondary': 'var(--on-secondary)',
        'on-secondary-container': 'var(--on-secondary)',
        'on-secondary-fixed': 'var(--on-secondary)',
        'on-secondary-fixed-variant': 'var(--on-secondary)',

        tertiary: 'var(--tertiary)',
        'tertiary-container': 'var(--tertiary)',
        'tertiary-fixed': 'var(--tertiary)',
        'tertiary-fixed-dim': 'var(--tertiary)',
        'tertiary-dim': 'var(--tertiary)',
        'on-tertiary': 'var(--on-surface)',
        'on-tertiary-container': 'var(--on-surface)',
        'on-tertiary-fixed': 'var(--on-surface)',
        'on-tertiary-fixed-variant': 'var(--on-surface)',

        surface: 'var(--surface)',
        'surface-dim': 'var(--surface)',
        'surface-bright': 'var(--surface-container-highest)',
        'surface-variant': 'var(--surface-container)',
        'surface-container-lowest': 'var(--background)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'surface-tint': 'var(--primary)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'on-background': 'var(--on-background)',
        background: 'var(--background)',
        'inverse-surface': 'var(--on-surface)',
        'inverse-on-surface': 'var(--on-surface-variant)',

        outline: 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',

        error: 'var(--error)',
        'error-container': 'var(--error)',
        'error-dim': 'var(--error)',
        'on-error': 'var(--on-error)',
        'on-error-container': 'var(--on-error)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}